# Site settings
title: Declan Webb
email: declanwebb22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Declan Webbs' Personal Website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://decweb.com" # the base hostname & protocol for your site
twitter_username: DeccyWebb
github_username:  DecWebb

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: false
disqus_shortname: ''

# Build settings
markdown: kramdown
